Define loading mode to speed up when loading data
hugegraph/hugegraph pull request #1188
Opened 2020-09-22 08:47 UTC by Linary

Change-Id: Ia9a93a3f0433c67353d89eb877a799ed5202fac1

2020-09-22 09:28 UTC, javeme requested changes

2020-09-22 09:28 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/StandardHugeGraph.java
> +        LOG.info("graph will work in {} mode", mode);
LOG.info("Graph {}  will work in {} mode", this, mode);

2020-09-23 06:31 UTC, javeme approved these changes

2020-09-23 07:13 UTC, zhoney approved these changes

2020-09-23 07:13 UTC, merged