Fix rocksdb instance not close properly
hugegraph/hugegraph pull request #1264
Opened 2020-11-16 09:54 UTC by Linary

* The open-pool opened session is always exist

Change-Id: I30504565155848659a818fbc1b57999547f0502f

2020-11-16 10:15 UTC, javeme commented on hugegraph-rocksdb/src/main/java/com/baidu/hugegraph/backend/store/rocksdb/RocksDBStore.java
> +        this.sessions.session();
add comments for why

2020-11-16 13:01 UTC, javeme requested changes

2020-11-16 13:01 UTC, javeme commented on hugegraph-rocksdb/src/main/java/com/baidu/hugegraph/backend/store/rocksdb/RocksDBStore.java
> +                                           () -> this.sessions.closeSession());
is it ok if there are multi disks

2020-11-17 02:59 UTC, Linary commented on hugegraph-rocksdb/src/main/java/com/baidu/hugegraph/backend/store/rocksdb/RocksDBStore.java
> +                                           () -> this.sessions.closeSession());
it's ok

2020-11-17 04:08 UTC, javeme approved these changes

2020-11-17 07:34 UTC, merged