export new implemented oltp traversals
hugegraph/hugegraph pull request #1289
Opened 2020-12-07 09:22 UTC by zhoney

Change-Id: I0e501dcffd7c38dbd6afe76e82000935160bee36

2020-12-09 05:58 UTC, javeme requested changes

2020-12-09 05:58 UTC, javeme commented on hugegraph-dist/src/assembly/static/conf/gremlin-server.yaml
> +          com.baidu.hugegraph.traversal.algorithm.CollectionPathsTraverser,
export EdgeStep

2020-12-09 05:58 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/TraverserAPI.java
> +              HugeGraph graph, TemplatePathsAPI.TemplatePathStep step) {
move to TemplatePathsAPI

2020-12-09 06:07 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/CountTraverser.java
> +    private Iterator<Edge> edgesOfVertexWithDedup(Id source, EdgeStep step) {
edgesOfVertexWithCount

2020-12-09 07:25 UTC, zhoney commented on hugegraph-dist/src/assembly/static/conf/gremlin-server.yaml
> +          com.baidu.hugegraph.traversal.algorithm.CollectionPathsTraverser,
already export

2020-12-09 08:06 UTC, javeme approved these changes

2020-12-09 09:30 UTC, Linary approved these changes

2020-12-09 11:54 UTC, merged

2024-05-29 02:50 UTC, dongma commented
gremlin出发oltp，能否提供一个gremlin语句触发的示例？