fix psotgresql init failed due to not exist same name db with user
hugegraph/hugegraph pull request #1293
Opened 2020-12-09 12:31 UTC by zhoney

Change-Id: I955fb0a474904470355b92dbc9bf3aa08ea4f61e
fixed: #1285

2020-12-10 03:58 UTC, javeme requested changes

2020-12-10 03:58 UTC, javeme commented on hugegraph-dist/src/assembly/static/conf/hugegraph.properties
> +#postgresql.connect_database=template1
prefer jdbc.connect_database

2020-12-10 03:58 UTC, javeme commented on hugegraph-postgresql/src/main/java/com/baidu/hugegraph/backend/store/postgresql/PostgresqlSessions.java
> +    }
move to mysql

2020-12-10 14:06 UTC, javeme approved these changes

2020-12-14 07:55 UTC, Linary approved these changes

2020-12-14 07:56 UTC, merged