Check if master node before schedule gremlin job
hugegraph/hugegraph pull request #1314
Opened 2020-12-25 08:54 UTC by Linary

Change-Id: I9ef3e1f3f4d30ae8b252a53c148b0b0759eff472

2020-12-25 14:01 UTC, javeme requested changes

2020-12-25 14:01 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskScheduler.java
> +    default public void checkRequirement(String op) {
don't set default

2020-12-28 06:32 UTC, javeme approved these changes

2020-12-28 06:42 UTC, houzhizhen approved these changes

2020-12-28 08:23 UTC, merged