add config for whether encoding number of primary keys
hugegraph/hugegraph pull request #1323
Opened 2021-01-05 08:22 UTC by zhoney

Change-Id: I07e113b7f29e0d38e5d362663046c755ea8dc751

2021-01-06 03:56 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/structure/HugeVertex.java
> +        boolean encodeNumber = ((HugeConfig) this.graph().configuration()).get(
don't call configuration() if enable auth

2021-01-06 03:56 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/structure/HugeVertex.java
> +        boolean encodeNumber = ((HugeConfig) this.graph().configuration()).get(
add method graph.option(CoreOptions.VERTEX_ENCODE_PK_NUMBER) and set whitelist

2021-01-06 04:05 UTC, javeme commented
please set related issue id

2021-01-06 11:25 UTC, javeme requested changes

2021-01-06 11:25 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/HugeGraphAuthProxy.java
> +        return this.hugegraph.option(option);
this.verifyStatusPermission();

2021-01-06 11:25 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/backend/tx/SchemaTransaction.java
> +    private boolean syncDelete() {
let asyncRun get it by option()

2021-01-06 11:25 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/schema/builder/AbstractBuilder.java
> +        return this.graph.option(CoreOptions.TASK_WAIT_TIMEOUT);
delete taskWaitTimeout() method

2021-01-06 11:25 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/structure/HugeFeatures.java
> +                                    .option(CoreOptions.VERTEX_DEFAULT_LABEL);
align with ".this"

2021-01-06 11:25 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/structure/HugeVertex.java
> +                                   .option(CoreOptions.VERTEX_ENCODE_PK_NUMBER);
move to line 203

2021-01-06 11:25 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/task/HugeTask.java
> +                                 .intValue();
change propertyLimit to long

2021-01-07 06:06 UTC, javeme approved these changes

2021-01-07 06:13 UTC, Linary approved these changes

2021-01-07 06:36 UTC, merged