fix ttl not work due to job not close tx
hugegraph/hugegraph pull request #1330
Opened 2021-01-12 08:10 UTC by zhoney

Change-Id: Ic4a3bc11e67f92c88772149d5c304a2c1da0ec64

2021-01-12 10:44 UTC, javeme requested changes

2021-01-12 10:44 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskCallable.java
> +        if (this.graph().tx().isOpen()) {
define tx first

2021-01-13 08:53 UTC, javeme approved these changes

2021-01-13 08:59 UTC, Linary approved these changes

2021-01-13 09:00 UTC, merged