Add TarLz4Util to improve perf for comressing snapshot
hugegraph/hugegraph pull request #1336
Opened 2021-01-18 07:57 UTC by Linary

Change-Id: I6d8d4d180a2216ad3c026e884e9e05bd6ed80eff

2021-01-19 11:50 UTC, javeme requested changes

2021-01-19 11:50 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/util/TarLZ4Util.java
> +public final class TarLZ4Util {
can we move all the methods of ZipUtil and TarLZ4Util to CompressUtil

2021-01-19 11:50 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/util/TarLZ4Util.java
> +             LZ4BlockOutputStream lz4os = new LZ4BlockOutputStream(bos, 8192,
define const var for 8192

2021-01-19 11:50 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/util/TarLZ4Util.java
> +            throw new IOException("File doesn't exists");
add the source to error message

2021-01-19 11:50 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/util/TarLZ4Util.java
> +             BufferedInputStream bis = new BufferedInputStream(cis);
what's the best buffer size

2021-01-22 09:04 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/util/CompressUtil.java
> +    public static void tarCompress(String rootDir, String sourceDir,
prefer compressTar

2021-01-30 09:09 UTC, zhoney requested changes

2021-01-30 09:09 UTC, zhoney commented on hugegraph-core/src/main/java/com/baidu/hugegraph/util/CompressUtil.java
> +            // Continue to read all remaining bytes(extra metadata of ZipEntry)
prefer /* */

2021-01-30 09:09 UTC, zhoney commented on hugegraph-core/src/main/java/com/baidu/hugegraph/util/CompressUtil.java
> +    private static void compressDirToZipFile(String rootDir,
prefer zipDir

2021-02-01 03:38 UTC, javeme approved these changes

2021-02-01 07:36 UTC, houzhizhen approved these changes

2021-02-03 07:44 UTC, merged