Bfs optimize vertex-out-out query
hugegraph/hugegraph pull request #1359
Opened 2021-02-19 12:06 UTC by javeme

2021-02-20 12:50 UTC, javeme commented
cassandra ci:
![image](https://user-images.githubusercontent.com/9625821/108596012-257e9d00-73bd-11eb-8c7d-b3ee6c4e76d7.png)

2021-02-24 03:06 UTC, javeme commented
rocksdb ci:
![image](https://user-images.githubusercontent.com/9625821/108941567-4f231700-7690-11eb-9ad5-a5fa4c5d1ccd.png)

2021-02-24 05:21 UTC, javeme commented
cassandra:
```
[ERROR] Tests run: 684, Failures: 2, Errors: 0, Skipped: 21, Time elapsed: 481.763 s <<< FAILURE! - in com.baidu.hugegraph.core.CoreTestSuite
[ERROR] testQueryEdgesWithLimitOnMultiLevel(com.baidu.hugegraph.core.EdgeCoreTest)  Time elapsed: 0.359 s  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<3>
	at com.baidu.hugegraph.core.EdgeCoreTest.testQueryEdgesWithLimitOnMultiLevel(EdgeCoreTest.java:1999)
[ERROR] testQueryEdgesAdjacentVerticesWithLimitAndFilterProp(com.baidu.hugegraph.core.EdgeCoreTest)  Time elapsed: 1.056 s  <<< FAILURE!
java.lang.AssertionError: expected:<9> but was:<11>
	at com.baidu.hugegraph.core.EdgeCoreTest.testQueryEdgesAdjacentVerticesWithLimitAndFilterProp(EdgeCoreTest.java:2398)
```
mysql
```java:
[ERROR] Tests run: 684, Failures: 2, Errors: 0, Skipped: 26, Time elapsed: 314.164 s <<< FAILURE! - in com.baidu.hugegraph.core.CoreTestSuite
[ERROR] testQueryEdgesWithLimitOnMultiLevel(com.baidu.hugegraph.core.EdgeCoreTest)  Time elapsed: 0.273 s  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<3>
	at com.baidu.hugegraph.core.EdgeCoreTest.testQueryEdgesWithLimitOnMultiLevel(EdgeCoreTest.java:1999)
[ERROR] testQueryEdgesAdjacentVerticesWithLimitAndFilterProp(com.baidu.hugegraph.core.EdgeCoreTest)  Time elapsed: 0.312 s  <<< FAILURE!
java.lang.AssertionError: expected:<9> but was:<11>
	at com.baidu.hugegraph.core.EdgeCoreTest.testQueryEdgesAdjacentVerticesWithLimitAndFilterProp(EdgeCoreTest.java:2398)
```

2021-02-25 08:36 UTC, Linary requested changes

2021-02-25 08:36 UTC, Linary commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepWithoutPath.java
> +            Function<Object, Traverser.Admin<Vertex>> nextFunc = null;
use java.util.Function

2021-02-25 08:36 UTC, Linary commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepWithoutPath.java
> +            Function<Object, Traverser.Admin<Vertex>> nextFunc = null;
remove `= null`, it's redudant

2021-02-25 08:36 UTC, Linary commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepWithoutPath.java
> +            List<Traverser.Admin<Vertex>> vertexes = new ArrayList<>();
replace with vertices

2021-02-25 08:36 UTC, Linary commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepWithoutPath.java
> +        for (Traverser.Admin<Vertex> t : traversers) {
t -> traverser

2021-04-19 10:02 UTC, Linary requested changes

2021-10-27 03:27 UTC, zhoney submitted a review, later dismissed

2021-11-03 07:34 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/HugeVertexStepByBatch.java
> +            assert queryEdge;
yes, it's just for comment

2021-11-03 09:51 UTC, imbajin approved these changes

2021-11-03 11:07 UTC, zhoney approved these changes

2021-11-03 11:09 UTC, merged