Fix NPE when init admin user
hugegraph/hugegraph pull request #1360
Opened 2021-02-20 07:22 UTC by Linary

Change-Id: I6fe0e341b5c6dfdb3d92b658cc13b470e8eb2a53

2021-02-20 11:47 UTC, javeme requested changes

2021-02-20 11:47 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/StandardAuthenticator.java
> +        hugeConfig.setProperty(CoreOptions.RAFT_MODE.name(), "false");
can't force set to false, since start-server also go here

2021-02-24 13:09 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/StandardAuthenticator.java
> +        HugeConfig hugeConfig = new HugeConfig(graphPath);
rename to graphConfig

2021-02-24 13:09 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/StandardAuthenticator.java
> +            hugeConfig.setProperty(CoreOptions.RAFT_MODE.name(), "false");
"false" => false

2021-02-24 13:10 UTC, javeme commented
also improve NPE code

2021-02-25 03:20 UTC, Linary commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/StandardAuthenticator.java
> +            hugeConfig.setProperty(CoreOptions.RAFT_MODE.name(), "false");
The option value must be String
```
private Object validateOption(String key, Object value) {
      E.checkArgument(value instanceof String,
                      "Invalid value for key '%s': %s", key, value);

      TypedOption<?, ?> option = OptionSpace.get(key);
      return option.parseConvert(value);
  }
```

2021-02-26 04:16 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/StandardAuthenticator.java
> +    private static final String INITING_STORE = "initing-store";
initing_store

2021-02-26 04:16 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/StandardAuthenticator.java
> +            // Forced set to false when initializing backend
Forced set RAFT_MODE to false

2021-02-26 04:16 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/StandardAuthenticator.java
> +            graphConfig.setProperty(CoreOptions.RAFT_MODE.name(), "false");
false

2021-02-26 06:47 UTC, Linary commented
![image](https://user-images.githubusercontent.com/9151831/109265406-779e4300-7841-11eb-992e-5e999c452403.png)

2021-02-26 07:59 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/StandardAuthenticator.java
> +            // Forced set RAFT_MODE to false
keep "when initializing backend"

2021-02-27 12:17 UTC, javeme approved these changes

2021-03-01 13:00 UTC, zhoney approved these changes

2021-03-02 03:24 UTC, merged