auth: fix resource type NONE and add resource type SCHEMA
hugegraph/hugegraph pull request #1362
Opened 2021-02-20 12:29 UTC by javeme

2021-02-22 06:20 UTC, houzhizhen requested changes

2021-02-22 06:20 UTC, houzhizhen commented on hugegraph-test/src/main/java/com/baidu/hugegraph/unit/core/RolePermissionTest.java
> +        Assert.assertTrue(ResourceType.ALL.match(ResourceType.ALL));;
duplicate with line 160, ALL -> ROOT

2021-02-22 06:20 UTC, houzhizhen commented on hugegraph-test/src/main/java/com/baidu/hugegraph/unit/core/RolePermissionTest.java
> +        Assert.assertFalse(ResourceType.ALL.match(ResourceType.ROOT));
ditto

2021-02-22 06:54 UTC, zhoney requested changes

2021-02-22 06:54 UTC, zhoney commented on hugegraph-api/src/main/java/com/baidu/hugegraph/auth/HugeAuthenticator.java
> +             * maybe also support:
add an empty line and ”In the future maybe also support:“

2021-02-23 08:56 UTC, houzhizhen approved these changes

2021-03-01 13:04 UTC, zhoney approved these changes

2021-03-02 06:49 UTC, Linary approved these changes

2021-03-02 06:50 UTC, merged