fix ScyllaDB: lost page results due to not fetched the entire page
hugegraph/hugegraph pull request #1407
Opened 2021-03-30 12:55 UTC by javeme

fix #1340

Change-Id: Ib89d9790af4236a137d9215e27f0d17f0de10afd

2021-03-30 12:56 UTC, javeme commented
why set remaining = getAvailableWithoutFetching(): https://support.datastax.com/hc/en-us/articles/115003076346-FAQ-Why-does-Java-driver-setFetchSize-return-all-rows-

2021-03-31 06:11 UTC, javeme commented
ci error of cassandra backend:
```
[ERROR] Tests run: 684, Failures: 1, Errors: 0, Skipped: 21, Time elapsed: 513.523 s <<< FAILURE! - in com.baidu.hugegraph.core.CoreTestSuite
[ERROR] testAddEdgeWithTtlAndTtlStartTime(com.baidu.hugegraph.core.EdgeCoreTest)  Time elapsed: 1.872 s  <<< FAILURE!
java.lang.AssertionError
	at com.baidu.hugegraph.core.EdgeCoreTest.testAddEdgeWithTtlAndTtlStartTime(EdgeCoreTest.java:754)

```

2021-04-07 12:33 UTC, javeme commented
TODO: ensure return the full page to users which scylla fetched to local.

2021-04-14 08:01 UTC, zhoney approved these changes

2021-04-25 07:03 UTC, zhoney requested changes

2021-04-25 07:03 UTC, zhoney commented on hugegraph-core/src/main/java/com/baidu/hugegraph/backend/page/PageState.java
> +        E.checkNotNull("page", "page");
E.checkNotNull(page, "page");

2021-04-25 13:37 UTC, zhoney approved these changes

2021-04-26 06:25 UTC, Linary approved these changes

2021-04-26 06:26 UTC, merged