Fix raft-tools script small bug
hugegraph/hugegraph pull request #1416
Opened 2021-04-08 10:08 UTC by Linary

Change-Id: I5b095d19f58b58113ae903578ad6a1377aa52119

2021-04-09 03:28 UTC, javeme approved these changes

2021-04-13 07:02 UTC, zhoney requested changes

2021-04-13 07:02 UTC, zhoney commented on hugegraph-dist/src/assembly/static/bin/raft-tools.sh
> +    echo "  -l,--list_peers \${graph} \${group}                    list all peers' endpoints for graph, can be used on leader or follower node"
keep “-”

2021-04-16 08:05 UTC, javeme approved these changes

2021-04-16 08:29 UTC, houzhizhen approved these changes

2021-04-16 11:46 UTC, zhoney approved these changes

2021-04-16 11:47 UTC, merged