fix style for raft module
hugegraph/hugegraph pull request #1423
Opened 2021-04-17 16:30 UTC by javeme

Change-Id: I36cf1e0093fb34837e5c5f46ace91c38eae10a74

2021-04-19 06:03 UTC, Linary requested changes

2021-04-19 06:03 UTC, Linary commented on hugegraph-core/src/main/java/com/baidu/hugegraph/backend/store/raft/RaftNode.java
> +        @SuppressWarnings("unused")
remove it. Don't write misleading annotation to shield warnings

2021-04-22 02:51 UTC, Linary approved these changes

2021-04-22 06:42 UTC, houzhizhen approved these changes

2021-04-23 09:13 UTC, merged