Zy dev
hugegraph/hugegraph pull request #1432
Opened 2021-04-27 09:51 UTC by zyxxoo

fix error hit and Integer case to Double

2021-04-27 09:57 UTC, Linary requested changes

2021-04-27 09:57 UTC, Linary commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/SingleSourceShortestPathTraverser.java
> +                edgeWeight = toDouble(edge.value(this.weight));
add this.

2021-04-28 07:02 UTC, zhoney approved these changes

2021-04-28 07:14 UTC, Linary approved these changes

2021-04-28 07:15 UTC, merged

2021-04-28 15:58 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/NeighborRankTraverser.java
> +                            "The top of each layer must be in (0, %s]",
perfect if prompt the actual top value

2021-04-28 15:58 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/SingleSourceShortestPathTraverser.java
> +        private double toDouble(Object obj) {
set static

2021-04-28 15:58 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/SingleSourceShortestPathTraverser.java
> +            return (double) obj;
prefer to call NumericUtil.toNumber(obj).doubleValue()