doc: unified naming of degree for olap algorithms
hugegraph/hugegraph pull request #1433
Opened 2021-04-27 11:27 UTC by imbajin

2021-04-27 12:35 UTC, Linary requested changes

2021-04-27 12:35 UTC, Linary commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/CountAPI.java
> +        public long maxDegree = Long.valueOf(DEFAULT_MAX_DEGREE);
replace Long.valueOf() -> Long.parseLong, remove redundant boxing

2021-04-28 16:22 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/CountAPI.java
> +        public long maxDegree = Long.valueOf(DEFAULT_MAX_DEGREE);
not addressed Linary's comment

2021-04-28 16:22 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/CustomizedCrosspointsAPI.java
> +        public long maxDegree = Long.valueOf(DEFAULT_MAX_DEGREE);
ditto

2021-04-28 16:22 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/FusiformSimilarityAPI.java
> +        E.checkArgument(request.maxDegree > 0 || request.maxDegree == NO_LIMIT,
0L

2021-04-28 16:22 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/PersonalRankAPI.java
> +                        "The maxDegree of rank request must be > 0, but got: %s",
The max_degree of rank request.
same as other check

2021-04-28 16:22 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/steps/WeightedEdgeStep.java
> +                        "Max degree must be greater than or equal to sample," +
The max_degree must...

2021-04-28 16:22 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/steps/WeightedEdgeStep.java
> +                        " but got max degree %s and sample %s",
max_degree

2021-05-06 13:23 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/PersonalRankAPI.java
> +                        " but got: %s", request.maxDegree);
prefer to put space to the previous line

2021-05-06 13:23 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/NeighborRankAPI.java
> +        @JsonProperty("max_degree")
keep compatible through alias "degree"

2021-05-06 13:23 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/TraverserAPI.java
> +        @JsonProperty("max_degree")
ditto

2021-05-06 13:23 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/PersonalRankAPI.java
> +        @JsonProperty("max_degree")
this param is not in a step, don't need alias

2021-05-06 13:23 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/CustomizedPathsAPI.java
> +        @JsonProperty("max_degree")
ditto

2021-05-06 13:23 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/CustomizedCrosspointsAPI.java
> +        @JsonProperty("max_degree")
ditto

2021-05-06 13:23 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/CountAPI.java
> +        @JsonProperty("max_degree")
keep compatible through alias "degree"
note import com.fasterxml.jackson.annotation.JsonAlias

2021-05-07 03:58 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/version/ApiVersion.java
> +     * [0.23] HugeGraph-1176: Support maxDegree and capacity for traverse api
don't update it

2021-05-07 03:58 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/version/ApiVersion.java
> +     * [0.32] Issue-250: Keep depth and maxDegree consistent for traverser api
ditto

2021-05-07 03:58 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/steps/WeightedEdgeStep.java
> +             Long.valueOf(DEFAULT_MAX_DEGREE), 0L, null, 0.0D,
also use parseLong?

2021-05-07 06:07 UTC, javeme approved these changes

2021-05-11 09:29 UTC, zhoney approved these changes

2021-05-11 09:31 UTC, zhoney commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/AllShortestPathsAPI.java
> +import static com.baidu.hugegraph.traversal.algorithm.HugeTraverser.DEFAULT_MAX_DEGREE;
prefer upgrade server api version

2021-05-11 11:43 UTC, zhoney requested changes

2021-05-11 11:43 UTC, zhoney commented on hugegraph-api/src/main/java/com/baidu/hugegraph/version/ApiVersion.java
> +     * [0.61] Issue-1433: Unify naming of degree for olap algorithms
olap -> oltp

2021-05-12 02:45 UTC, zhoney approved these changes

2021-05-12 04:19 UTC, javeme approved these changes

2021-05-12 06:14 UTC, Linary approved these changes

2021-05-12 06:15 UTC, merged