Fix Fusiform similarity api return all vertices when similars is empty
hugegraph/hugegraph pull request #1434
Opened 2021-04-27 11:41 UTC by zyxxoo

Fix Fusiform similarity api return all vertices when similars is empty

2021-04-27 13:06 UTC, zhoney requested changes

2021-04-27 13:06 UTC, zhoney commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/FusiformSimilarityAPI.java
> +        if (request.withVertex && !result.isEmpty()) {
prefer:
```
Set<Id> vertices = result.vertices();
if (request.withVertex && !vertices.isEmpty()) {
    iterator = g.vertices(vertices.toArray());
}
```

2021-04-28 03:41 UTC, zhoney approved these changes

2021-04-28 03:43 UTC, Linary approved these changes

2021-04-28 03:43 UTC, merged