doc: use 3 issue template for better community experience
hugegraph/hugegraph pull request #1453
Opened 2021-05-18 12:11 UTC by imbajin

At present, there are 3 issue template and 1 config file:
- Bug Report
- Feature Request
- Ask question (Guide)

And simplify the issue template to improve the user's willingness to fill in

2021-05-18 12:23 UTC, zhoney requested changes

2021-05-18 12:23 UTC, zhoney commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-server.html
change to API link

2021-05-18 12:23 UTC, zhoney commented on .github/ISSUE_TEMPLATE/bug_report.md
> +## How to reproduce ( 复现方式 )
复现方式->复现步骤

2021-05-18 12:33 UTC, javeme commented on .github/ISSUE_TEMPLATE/bug_report.md
> +> 3. 请关注提交的 issue, 缺乏信息 / 长时间 ( > 14 天) 没有回复, issue 可能会被 **关闭**
增加：被关闭之后，可以随时 reopen 重新打开。

2021-05-18 12:33 UTC, javeme commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: '[BUG] short description'
improve "short description", if it to be filled, like "Type summary description here" is ok

2021-05-18 12:33 UTC, javeme commented on .github/ISSUE_TEMPLATE/bug_report.md
> +> 1. 请先**搜索**, 并**确认**现有的 [issue](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有与您相同 / 相关的问题, 勿重复提交
[Issues]

2021-05-18 12:33 UTC, javeme commented on .github/ISSUE_TEMPLATE/bug_report.md
> +// JSON Vertex / Edge ⬇
JSON of Vertex or Edge

2021-05-18 12:33 UTC, javeme commented on .github/ISSUE_TEMPLATE/bug_report.md
> +// JSON Schema ⬇
JSON of Schema

2021-05-18 12:33 UTC, javeme commented on .github/ISSUE_TEMPLATE/config.yml
> +# 是否允许创建空白的 issue
remove this comment

2021-05-18 12:33 UTC, javeme commented on .github/ISSUE_TEMPLATE/feature_request.md
> +title: '[Feature] short description'
ditto

2021-05-18 12:33 UTC, javeme commented on .github/ISSUE_TEMPLATE/question_ask.md
> +title: '[Question] short description'
ditto

2021-05-18 13:48 UTC, javeme approved these changes

2021-05-19 11:31 UTC, Linary approved these changes

2021-05-20 08:44 UTC, zhoney approved these changes

2021-05-20 08:45 UTC, merged