refact: remove source vertex from kout algorithm
hugegraph/hugegraph pull request #1463
Opened 2021-05-24 13:06 UTC by imbajin

also adapt test in client

2021-05-25 08:53 UTC, imbajin commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/KoutTraverser.java
>          latest.add(sourceV);
won't return sourceV in any cases now

2021-05-25 13:02 UTC, zhoney requested changes

2021-05-25 13:02 UTC, zhoney commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/HugeTraverser.java
> +                boolean exist = (excluded != null && excluded.contains(kNode));
rename `exist` to `matchExcluded` or `inExcluded`

2021-05-26 07:50 UTC, zhoney approved these changes

2021-05-26 14:54 UTC, Linary approved these changes

2021-05-27 04:08 UTC, javeme requested changes

2021-05-27 04:08 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/PersonalRankAPI.java
> +                        "or == -1, but got: %s", request.maxDegree);
don't need "or == -1", expected all the checks keep the same style

2021-05-27 04:08 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/HugeTraverser.java
> +                            "The max degree must be < capacity");
max_degree

2021-05-27 04:08 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/NeighborRankTraverser.java
> +                            "The max degree must be > 0, but got %s",
max_degree

2021-05-27 04:08 UTC, javeme commented on hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/algorithm/steps/EdgeStep.java
> +                        "The max degree must be > 0 or == -1, but got: %s",
max_degree

2021-05-27 07:50 UTC, zhoney submitted a review, later dismissed

2021-05-27 08:11 UTC, javeme commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/traversers/CountAPI.java
> +                               "The dedupSize of request " +
dedup size

2021-05-27 09:07 UTC, zhoney approved these changes

2021-05-27 09:17 UTC, javeme approved these changes

2021-05-27 09:36 UTC, merged