Improve check for getting vertex when create edge
hugegraph/hugegraph pull request #1477
Opened 2021-06-02 11:05 UTC by Linary

Change-Id: I86b7ac068154c52faf0d0d7f035cbf08178bf0d8

2021-06-03 03:27 UTC, javeme submitted a review, later dismissed

2021-06-03 13:22 UTC, zhoney requested changes

2021-06-03 13:22 UTC, zhoney commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/graph/EdgeAPI.java
> +        if (vertex.label().equals(label)) {
```
if (!vertex.label().equals(label)) {
```

2021-06-08 07:07 UTC, javeme submitted a review, later dismissed

2021-06-09 09:35 UTC, javeme approved these changes

2021-06-09 09:36 UTC, javeme approved these changes

2021-06-09 09:38 UTC, zhoney approved these changes

2021-06-09 09:39 UTC, merged