add unit test for traversers api
hugegraph/hugegraph pull request #1489
Opened 2021-06-04 07:35 UTC by zyxxoo

add unit test (allshortestPath, countAPI, CrosspointsAPI, CustomizedCrosspointsAPI)

2021-06-08 04:05 UTC, javeme requested changes

2021-06-08 04:05 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/AllShortestPathsAPITest.java
> +    public static String path = "graphs/hugegraph/traversers/allshortestpaths";
fix code style https://github.com/hugegraph/hugegraph-doc/wiki/HugeGraph%E4%BB%A3%E7%A0%81%E9%A3%8E%E6%A0%BC%E6%8C%87%E5%8D%97

2021-06-08 04:05 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +                                          entry.getKey(), entry.getValue()))
improve align

2021-06-08 04:05 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +        System.out.println(ret);
not allowed println

2021-06-08 04:05 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +                                            map -> map.get("id").toString()));
align

2021-06-08 04:05 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +        if (r.getStatus() != 200) {
assert them

2021-06-09 10:25 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/AllShortestPathsAPITest.java
> +                                                  String.format("\"%s\"",
add method id2Json()

2021-06-09 10:25 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +    protected static Map<String, String> getAllName2VertexIds() {
allVertexName2IdMap

2021-06-09 10:25 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/AllShortestPathsAPITest.java
> +        Map<String, Object> map = ImmutableMap.of("source",
rename to params

2021-06-09 10:25 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/CountAPITest.java
> +                                       "\t\"source\": \"%s\",\n" +
improve style

2021-06-09 10:25 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/CrosspointsAPITest.java
> +                (List<Map<String, Object>>) data.get("crosspoints");
call assertContains

2021-06-09 15:31 UTC, javeme requested changes

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +
empty line

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +    protected static Map<String, String> listAllName2VertexIds() {
listAllVertexName2Ids

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +        Map<String, String> ret = new HashMap<>();
improve var name

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/AllShortestPathsAPITest.java
> +                                                  String.format("\"%s\"",
not addressed: add method id2Json()

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/CountAPITest.java
> +                                       "}", markoId);
keep the same style

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/FusiformSimilarityAPITest.java
> +                                         "    }, " +
ditto

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/EdgesAPITest.java
> +                                  ImmutableMap.of("vertex_id",
define var params first

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/CustomizedCrosspointsAPITest.java
> +                                       "        } " +
ditto

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/ApiTestSuite.java
> +    UserApiTest.class,
add TraversersAPITestSuite

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/TraversersAPITestSuite.java
> +public class TraversersAPITestSuite {
rename to TraversersApiTestSuite

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/JaccardSimilarityAPITest.java
> +                                                                      markoId),
ditto

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +    protected static Map<String, Object> parseMap(String json) {
delete this method and call assertJsonContains() instead

2021-06-09 15:31 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/CountAPITest.java
> +        Integer count = (Integer) entity.get("count");
call assertJsonContains(content, "count")

2021-06-10 05:26 UTC, zyxxoo commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/AllShortestPathsAPITest.java
> +                                                  String.format("\"%s\"",
之前有考虑过封装， 但是想这里看起来直观一点就么封装函数了

2021-06-10 05:35 UTC, zyxxoo commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +    protected static Map<String, Object> parseMap(String json) {
这里可以考虑下保留，assertJsonContains 适合只有一个key的地方，多个key的时候 assertJson 要解析多次，而且有的时候只需要验证size >0 就可以，用 assertJsonContains 做不到，我现在将只需拿一个值的地方都改成了 assertJsonContains, 其他地方还是用的 解析 map的方式来做

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +            throws IOException {
align

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +                        "Can't find value of the key: %s in json.", key));
ditto

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/BaseApiTest.java
> +                    "Failed to deserialize %s", content), e);
ditto

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/AllShortestPathsAPITest.java
> +
one empty line

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/AllShortestPathsAPITest.java
> +package com.baidu.hugegraph.api.traversers;
add license header

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/CountAPITest.java
> +import static com.baidu.hugegraph.testutil.Assert.assertEquals;
don' import static as possible

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/EdgesAPITest.java
> +                                  ImmutableMap.of("vertex_id",
define var params first

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/EdgesApiTest.java
> +                                      + "/edges/shards";
move "+" to previous line

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/EdgesAPITest.java
> +    final static String EDGE_PATH = "graphs/hugegraph/traversers/edges";
set public, can define base class TraverserApiTest

2021-06-10 08:13 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/TraversersApiTestSuite.java
> +    public static void initEnv() {
delete this method and add TraversersApiTestSuite into ApiTestSuite

2021-06-25 11:06 UTC, javeme requested changes

2021-06-25 11:06 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/KneighborApiTest.java
> +                                       "  \"labels\": [\"knows\", " +
keep same style

2021-06-25 11:06 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/KoutApiTest.java
> +                                       "  \"labels\": [\"knows\", " +
ditto

2021-06-25 11:06 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/PathsApiTest.java
> +        Assert.assertFalse(paths.isEmpty());
Assert.assertEquals(xx, paths.size());

2021-06-25 11:06 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/PersonalRankApiTest.java
> +        Assert.assertNotNull(entity);
assert more results content

2021-06-25 11:06 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/RingsApiTest.java
> +        Assert.assertFalse(rings.isEmpty());
ditto

2021-06-25 11:06 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/ShortestPathApiTest.java
> +public class ShortestPathApiTest extends BaseApiTest {
no test case

2021-06-25 11:06 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/SingleSourceShortestPathApiTest.java
> +public class SingleSourceShortestPathApiTest extends BaseApiTest {
ditto

2021-06-25 11:06 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/TemplatePathsApiTest.java
> +public class TemplatePathsApiTest extends BaseApiTest {
ditto

2021-06-30 07:51 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/KoutApiTest.java
> +        // Test for nearest is false
nearest=false

2021-06-30 07:51 UTC, javeme commented on hugegraph-dist/pom.xml
> +                    <artifactId>protobuf-java</artifactId>
which package is it from

2021-07-15 07:23 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/WeightedShortestPathApiTest.java
> +    final static String path = "graphs/hugegraph/traversers/" +
define var TRAVERSERS_API = "graphs/hugegraph/traversers/"

2021-07-15 07:23 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/SingleSourceShortestPathApiTest.java
> +        Map<String, Map> paths = assertJsonContains(respBody,"paths");
expect space

2021-07-15 07:23 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/SingleSourceShortestPathApiTest.java
> +        String respBody = assertResponseStatus(200, r);
String content

2021-07-15 07:23 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/SingleSourceShortestPathApiTest.java
> +        Assert.assertFalse(paths.isEmpty());
assert paths.size()

2021-07-15 07:23 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/WeightedShortestPathApiTest.java
> +        String respBody = assertResponseStatus(200, r);
ditto

2021-07-15 07:23 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/WeightedShortestPathApiTest.java
> +        Map<String, Map> paths = assertJsonContains(respBody,"path");
ditto

2021-07-15 07:23 UTC, javeme commented on hugegraph-test/src/main/java/com/baidu/hugegraph/api/traversers/ShortestPathApiTest.java
> +        Assert.assertFalse(paths.isEmpty());
can assert the size and elements?

2021-08-04 06:00 UTC, javeme approved these changes

2021-08-06 03:51 UTC, zhoney approved these changes

2021-08-06 04:02 UTC, merged