refactor: optimizing code of project update api
hugegraph/hugegraph pull request #1537
Opened 2021-07-07 11:24 UTC by zyxxoo

2021-07-12 09:07 UTC, Linary submitted a review, later dismissed

2021-07-12 09:20 UTC, zhoney requested changes

2021-07-12 09:20 UTC, zhoney commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/auth/ProjectAPI.java
> +                            "The action '%s' parameter can only be either " +
```
"The action parameter can only be either %s or %s or '', but got '%s'", 
ProjectAPI.ACTION_ADD_GRAPH, ProjectAPI.ACTION_REMOVE_GRAPH, action);
```

2021-07-14 02:57 UTC, Linary approved these changes

2021-07-14 03:29 UTC, corgiboygsj approved these changes

2021-07-14 03:35 UTC, zhoney approved these changes

2021-07-14 03:59 UTC, merged