Bugfix branch
hugegraph/hugegraph pull request #1627
Opened 2021-11-02 03:33 UTC by z7658329

Fix bug: mysql statement leak

fix #1626

2021-11-02 04:06 UTC, javeme reviewed
Looks good, thank you for your contribution.

2021-11-02 04:06 UTC, javeme commented on hugegraph-palo/src/main/java/com/baidu/hugegraph/backend/store/palo/PaloSessions.java
> +                }
seems lack of ResultSetWrapper file

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlEntryIterator.java
> +            while (!this.results.isClosed() && this.results.next()) {
move `!this.results.isClosed()` into next() method

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +    public boolean isClosed() throws SQLException {
merge into next()

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +    public ResultSet getResultSet() {
keep resultSet() style

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +    public void setResultSet(ResultSet resultSet) {
remove it

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +    }
remove them

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +    private Statement statement;
set final

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java
> +            } catch (SQLException sqlException) {
SQLException e

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java
> +                Statement statement = this.conn.createStatement();
move out of try-catch

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java
> +                throw sqlException;
close statement if exception occurred when executeQuery()

2021-11-02 07:11 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlTables.java
> +                ResultSet resultSet = results.getResultSet();
ResultSet rs

2021-11-02 08:05 UTC, zhoney requested changes

2021-11-02 08:05 UTC, zhoney commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +
delete empty line

2021-11-02 08:05 UTC, zhoney commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +                    "Failed to close resultSet and statement", e);
Failed to close resultSet or Statement

also prefer align " with BackendException in prior line

2021-11-02 08:06 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlEntryIterator.java
>              while (!this.results.isClosed() && this.results.next()) {
can remove `!this.results.isClosed() &&` since done in results.next()

2021-11-02 08:06 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +                    "Failed to close resultSet and statement", e);
align with "new" and keep "ResultSet and Statement"

2021-11-02 08:06 UTC, javeme commented on hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/ResultSetWrapper.java
> +            }
move to finally-block

2021-11-02 08:06 UTC, javeme commented on hugegraph-palo/src/main/java/com/baidu/hugegraph/backend/store/palo/PaloSessions.java
> +                ResultSet resultSet = results.resultSet();
also keep `ResultSet rs`

2021-11-02 09:23 UTC, javeme approved these changes

2021-11-03 03:43 UTC, zhoney approved these changes

2021-11-03 06:11 UTC, imbajin approved these changes

2021-11-03 06:19 UTC, merged